version: '3'
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    networks:
      - spring
  gateway:
    build: gateway/
    ports:
     - "7775:7775"
    depends_on:
      - consul
    links:
      - consul:consul
    networks:
      - spring
  hotels:
    build: hotels/
    ports:
     - "7777"
    depends_on:
      - consul
      - gateway
    links:
      - consul:consul
    networks:
      - spring
  bookings:
    build: bookings/
    ports:
     - "7774"
    depends_on:
      - consul
      - gateway
    links:
      - consul:consul
      - hotels:hotels
    networks:
      - spring
  prometheus:
    image: prom/prometheus:v2.0.0
    ports:
      - "9090:9090"
    depends_on:
      - consul
    links:
      - consul
    networks:
      - spring

networks:
 spring:
  external: true


# consul agent -dev -advertise 127.0.0.1
