server:
  port: ${PORT:7774}


spring:
  application:
    name: bookings-service
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: consul
      port: ${CONSUL_PORT:8500}
    inetutils:
      preferred-networks:
        - 192.168
        - 10.0
    loadbalancer:
      retry:
        enabled: true

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
client:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true
ribbon:
  eager-load:
    enabled: true

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000
#        loggerLevel: basic